#!/usr/bin/env bash
# check.sh -- Prerequisite check for ansible.builtin.copy
# Generated by AnsibleClaw
set -euo pipefail

MODULE="ansible.builtin.copy"
COLLECTION=""
PASS=0
FAIL=0

check() {
    local label="$1"
    shift
    if "$@" > /dev/null 2>&1; then
        echo "  [PASS] $label"
        PASS=$((PASS + 1))
    else
        echo "  [FAIL] $label"
        FAIL=$((FAIL + 1))
    fi
}

echo "Checking prerequisites for $MODULE ..."
echo

check "ansible CLI is installed" command -v ansible
check "ansible-doc CLI is installed" command -v ansible-doc
check "Module $MODULE is available" ansible-doc -t module "$MODULE"

if [[ -n "$COLLECTION" ]]; then
    check "Collection $COLLECTION is installed" \
        bash -c "ansible-galaxy collection list 2>/dev/null | grep -q '$COLLECTION'"
fi

echo
echo "Results: $PASS passed, $FAIL failed"

if [[ $FAIL -gt 0 ]]; then
    echo
    echo "To fix:"
    echo "  pip install ansible-core        # install Ansible"
    exit 1
fi
